apiVersion: v1
kind: Service
metadata:
  name: mypizza-service
spec:
  selector:
    app: mypizza
  ports:
    - name: http
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypizza-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mypizza
  template:
    metadata:
      labels:
        app: mypizza
    spec:
      containers:
        - name: mypizza
          image: nicolassss/mypizza.eatsout.com
          ports:
            - containerPort: 80


